/*
 * DC_MOTOR_Type.h
 *
 *  Created on: 14 Sep 2022
 *      Author: yabul
 */

#ifndef SOURCES_2_ECUAL_DC_MOTOR_INCLUDES_DC_MOTOR_TYPE_H_
#define SOURCES_2_ECUAL_DC_MOTOR_INCLUDES_DC_MOTOR_TYPE_H_

typedef enum
{
	DC_MOTOR_A,
	DC_MOTOR_B

}DC_MOTOR_T;


#endif /* SOURCES_2_ECUAL_DC_MOTOR_INCLUDES_DC_MOTOR_TYPE_H_ */
